[package]
name = "cosmicc-l21-execution"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
saltwater-sia = { path = "../../saltwater-sia" }
lighting-simulation = { git = "https://github.com/nickik/LightingSimulation", rev = "93a565c687f61d4e758af81bbde59ce5c4770996" }

