[package]
name = "cosmicc-l21-execution"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "cosmicc-l21-execution"

[workspace]

[dependencies]
saltwater-sia = { path = "../../saltwater-sia" }
lighting-simulation = { git = "https://github.com/nickik/LightingSimulation", rev = "7a0c16aff324f678a72a05df163c208f8031914f" }
