[package]
name = "saltwater-sia"
version = "0.12.0"
edition = "2018"
description = "Cosmic C lowering from typed C HIR to SIA32 machine code"

[lib]
path = "lib.rs"

[dependencies]
cranelift-codegen = { git = "https://github.com/nickik/crainlift", rev = "0ceb1975dc43079545ccae4621706f1def62d72b", features = ["std", "sia32"] }
cranelift-frontend = { git = "https://github.com/nickik/crainlift", rev = "0ceb1975dc43079545ccae4621706f1def62d72b" }
saltwater-parser = { path = "../saltwater-parser", version = "0.11.0" }
target-lexicon = { git = "https://github.com/nickik/crainlift", rev = "0ceb1975dc43079545ccae4621706f1def62d72b", package = "target-lexicon" }
