[package]
name = "saltwater-sia"
version = "0.12.0"
edition = "2018"
description = "Cosmic C lowering from typed C HIR to SIA32 machine code"

[lib]
path = "lib.rs"

[dependencies]
cranelift-codegen = { git = "https://github.com/nickik/crainlift", rev = "a974f1e131091e3dc384148d3dbf9cdb7dbd82a8", features = ["std", "sia32"] }
cranelift-frontend = { git = "https://github.com/nickik/crainlift", rev = "a974f1e131091e3dc384148d3dbf9cdb7dbd82a8" }
saltwater-parser = { path = "../saltwater-parser", version = "0.11.0" }
target-lexicon = { git = "https://github.com/nickik/crainlift", rev = "a974f1e131091e3dc384148d3dbf9cdb7dbd82a8", package = "target-lexicon" }
