[package]
name = "saltwater-sia"
version = "0.12.0"
edition = "2018"
description = "Cosmic C lowering from typed C HIR to SIA32 machine code"

[lib]
path = "lib.rs"

[dependencies]
cranelift-codegen = { git = "https://github.com/nickik/crainlift", rev = "9c26ade81cdf8223ccbc68eae7effd6c9ebe93c3", features = ["std", "sia32"] }
cranelift-frontend = { git = "https://github.com/nickik/crainlift", rev = "9c26ade81cdf8223ccbc68eae7effd6c9ebe93c3" }
saltwater-parser = { path = "../saltwater-parser", version = "0.11.0" }
target-lexicon = { git = "https://github.com/nickik/crainlift", rev = "9c26ade81cdf8223ccbc68eae7effd6c9ebe93c3", package = "target-lexicon" }
