[package]
name = "saltwater-amd64"
version = "0.13.0"
edition = "2021"
[lib]
path = "lib.rs"
[dependencies]
cranelift-codegen = { git = "https://github.com/nickik/crainlift", rev = "5c3dc85e79c6502e83e3210a9a29b5aabbc0d441", features = ["std", "x86"] }
cranelift-frontend = { git = "https://github.com/nickik/crainlift", rev = "5c3dc85e79c6502e83e3210a9a29b5aabbc0d441" }
cranelift-module = { git = "https://github.com/nickik/crainlift", rev = "5c3dc85e79c6502e83e3210a9a29b5aabbc0d441" }
cranelift-object = { git = "https://github.com/nickik/crainlift", rev = "5c3dc85e79c6502e83e3210a9a29b5aabbc0d441" }
target-lexicon = { git = "https://github.com/nickik/crainlift", rev = "5c3dc85e79c6502e83e3210a9a29b5aabbc0d441" }
saltwater-parser = { path = "../saltwater-parser" }
