#!/usr/bin/env python3
"""Compare integer-only adaptation with unmodified SoftFloat3e and emit guest vectors."""
import argparse, ctypes, hashlib, json, random, subprocess
from pathlib import Path
p=argparse.ArgumentParser(description=__doc__)
p.add_argument('--output',type=Path,required=True)
p.add_argument('--random-cases',type=int,default=100000)
a=p.parse_args(); root=Path(__file__).resolve().parent; out=a.output.resolve()
out.mkdir(parents=True,exist_ok=False)
manifest=json.loads((root/'upstream/SHA256.json').read_text())
for name,h in manifest.items():
 if hashlib.sha256((root/'upstream'/name).read_bytes()).hexdigest()!=h: p.error('upstream source changed: '+name)
files=['f32_add.c','s_addMagsF32.c','s_subMagsF32.c','s_roundPackToF32.c','s_normRoundPackToF32.c','s_shiftRightJam32.c','s_countLeadingZeros32.c','s_countLeadingZeros8.c','softfloat_state.c','ARM-VFPv2/s_propagateNaNF32UI.c','ARM-VFPv2/softfloat_raiseFlags.c']
cmd=['cc','-std=c99','-O2','-fPIC','-shared','-DINLINE_LEVEL=1','-I'+str(root/'upstream'),'-I'+str(root/'upstream/include'),'-I'+str(root/'upstream/ARM-VFPv2'),*[str(root/'upstream'/f) for f in files],str(root/'oracle.c'),str(root/'binary32-add.c'),str(root/'context.c'),'-o',str(out/'oracle.so')]
subprocess.run(cmd,check=True)
lib=ctypes.CDLL(str(out/'oracle.so')); U=ctypes.c_uint
class Context(ctypes.Structure):_fields_=[('flags',U),('rounding',U)]
lib.cosmic_sf_reference_add32.argtypes=[U,U,ctypes.POINTER(U)];lib.cosmic_sf_reference_add32.restype=U
lib.cosmic_sf_add32.argtypes=[ctypes.POINTER(Context),U,U];lib.cosmic_sf_add32.restype=U
# Independent transparent anchors, not generated from a host floating operation.
anchors=[(0,0,0,0),(0x80000000,0x80000000,0x80000000,0),(0x80000000,0,0,0),
 (0x3f800000,0x3f800000,0x40000000,0),(0x3f800000,0xbf800000,0,0),
 (1,1,2,0),(0x007fffff,1,0x00800000,0),(0x00800000,0x80000001,0x007fffff,0),
 (0x3f800000,0x33800000,0x3f800000,1),(0x3f800001,0x33800000,0x3f800002,1),
 (0x7f7fffff,0x7f7fffff,0x7f800000,5),(0x7f800000,0xff800000,0x7fc00000,16),
 (0x7fc12345,0x3f800000,0x7fc12345,0),(0x7f812345,0x3f800000,0x7fc12345,16)]
edges=[0,0x80000000,1,2,0x007fffff,0x00800000,0x00800001,0x3f000000,
 0x3f7fffff,0x3f800000,0x3f800001,0x40000000,0x33800000,0x33000000,
 0x7f7fffff,0xff7fffff,0x7f800000,0xff800000,0x7fc12345,0xffc12345,
 0x7f812345,0xff812345,0x7fffffff,0xffffffff,0xbf800000,0x80800000]
seed=20261005;rng=random.Random(seed);pairs=[(x,y) for x in edges for y in edges]
pairs += [(rng.getrandbits(32),rng.getrandbits(32)) for _ in range(a.random_cases)]
vectors=[]
def check(x,y,expected=None):
 flags=U();ref=lib.cosmic_sf_reference_add32(x,y,ctypes.byref(flags))
 if expected is not None: assert (ref,flags.value)==expected,(hex(x),hex(y),'anchor',hex(ref),flags.value,expected)
 ctx=Context(8);got=lib.cosmic_sf_add32(ctypes.byref(ctx),x,y)
 assert (got,ctx.flags)==(ref,flags.value|8),(hex(x),hex(y),hex(got),hex(ref),ctx.flags,flags.value)
 # Independent context remains unchanged, and per-operation output flags combine
 # with prior sticky state rather than resetting task state.
 return [x,y,ref,flags.value]
for x,y,r,f in anchors:vectors.append(check(x,y,(r,f)))
for i,(x,y) in enumerate(pairs):
 v=check(x,y)
 if i<len(edges)**2 or (i-len(edges)**2)<64:vectors.append(v)
lines=['/* Generated by check-add32.py from unmodified SoftFloat3e ARM-VFPv2. */',
 'static const unsigned int cosmic_sf_add32_vectors[][4] = {']
lines += ['    {'+', '.join('0x%08xu'%v for v in row)+'},' for row in vectors]
lines+=['};','#define COSMIC_SF_ADD32_VECTOR_COUNT %du'%len(vectors)]
(out/'add32-vectors.h').write_text('\n'.join(lines)+'\n')
report={'status':'passed','oracle':'unmodified SoftFloat3e ARM-VFPv2 integer source closure',
 'rounding':'nearest ties to even','tininess':'after rounding','seed':seed,
 'anchor_cases':len(anchors),'edge_cases':len(edges)**2,'random_cases':a.random_cases,
 'guest_vectors':len(vectors),'vector_sha256':hashlib.sha256((out/'add32-vectors.h').read_bytes()).hexdigest(),
 'command':cmd,'upstream_sources':manifest,'adapted_sources':{str(f.relative_to(root)):hashlib.sha256(f.read_bytes()).hexdigest() for f in [root/'binary32-add.c',root/'context.c',*sorted((root/'adapted').glob('*.inc'))]}}
(out/'summary.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps({k:report[k] for k in ['status','anchor_cases','edge_cases','random_cases','guest_vectors']}))
